# 系统信息
host: 0.0.0.0

# 网站信息
url: http://www.lijianhang.top
title: "李舰航的个人主页"
keywords: "李舰航,java,大数据常用框架,python,数据分析,hadoop,spark,kafka,flume,nginx"
description: "李舰航的个人主页，用于存放在学习中遇到的问题，涉及面会包含java,大数据，python，数据分析，后续还会涉及到机器学习，人工智能等。"

# 分页
paginate: 10
paginate_path: "/pages/page/:num"

# 作品
collections:
  work:
    output: true
    permalink: /pages/:collection/:name

# 构建
markdown: kramdown
highlighter: rouge
encoding: UTF-8
excerpt_separator: <!--excerpt-->
permalink: /pages/posts/:year/:month/:day/:title:output_ext
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# 排除
exclude:
 - Gemfile
 - Gemfile.lock
 - README.md
